ANIMALS_BRED : true
ANIMALS_BRED_NAME: ANIMALS_BRED

ARMOR_CLEANED: true
AVIATE_ONE_CM: true
BANNER_CLEANED: true
BEACON_INTERACTION: true
BELL_RING: true
BOAT_ONE_CM: true
BREAK_ITEM: false
BREWINGSTAND_INTERACTION: true
CAKE_SLICES_EATEN: true
CAULDRON_FILLED: true
CAULDRON_USED: true
CHEST_OPENED: true
CLEAN_SHULKER_BOX: true
CLIMB_ONE_CM: true
CRAFT_ITEM: false
CRAFTING_TABLE_INTERACTION: true
CROUCH_ONE_CM: true
DAMAGE_ABSORBED: true
DAMAGE_BLOCKED_BY_SHIELD: true
DAMAGE_DEALT: true
DAMAGE_DEALT_ABSORBED: true
DAMAGE_DEALT_RESISTED: true
DAMAGE_RESISTED: true
DAMAGE_TAKEN: true
DEATHS: true
DISPENSER_INSPECTED: true
DROP: false
DROP_COUNT: true
DROPPER_INSPECTED: true
ENDERCHEST_OPENED: true
ENTITY_KILLED_BY: false
FALL_ONE_CM: true
FISH_CAUGHT: true
FLOWER_POTTED: true
FLY_ONE_CM: true
FURNACE_INTERACTION: true
HOPPER_INSPECTED: true
HORSE_ONE_CM: true
INTERACT_WITH_ANVIL: true
INTERACT_WITH_BLAST_FURNACE: true
INTERACT_WITH_CAMPFIRE: true
INTERACT_WITH_CARTOGRAPHY_TABLE: true
INTERACT_WITH_GRINDSTONE: true
INTERACT_WITH_LECTERN: true
INTERACT_WITH_LOOM: true
INTERACT_WITH_SMITHING_TABLE: true
INTERACT_WITH_SMOKER: true
INTERACT_WITH_STONECUTTER: true
ITEM_ENCHANTED: true
JUMP: true
KILL_ENTITY: false
LEAVE_GAME: true
MINE_BLOCK: false
MINECART_ONE_CM: true
MOB_KILLS: true
NOTEBLOCK_PLAYED: true
NOTEBLOCK_TUNED: true
OPEN_BARREL: true
PICKUP: false
PIG_ONE_CM: true
PLAY_ONE_MINUTE: true
PLAYER_KILLS: true
RAID_TRIGGER: true
RAID_WIN: true
RECORD_PLAYED: true
SHULKER_BOX_OPENED: true
SLEEP_IN_BED: true
SNEAK_TIME: true
SPRINT_ONE_CM: true
STRIDER_ONE_CM: true
SWIM_ONE_CM: true
TALKED_TO_VILLAGER: true
TARGET_HIT: true
TIME_SINCE_DEATH: true
TIME_SINCE_REST: true
TRADED_WITH_VILLAGER: true
TRAPPED_CHEST_TRIGGERED: true
USE_ITEM: false
WALK_ON_WATER_ONE_CM: true
WALK_ONE_CM: true
WALK_UNDER_WATER_ONE_CM: true

timer: 1000
#tick